version: "3.8"

services:
  # -------------------------------
  # RabbitMQ
  # -------------------------------
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # -------------------------------
  # Redis
  # -------------------------------
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # -------------------------------
  # MongoDB
  # -------------------------------
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # -------------------------------
  # Domain Service
  # -------------------------------
  domain-service:
    build: ./domain-service
    container_name: domain-service
    ports:
      - "9091:9090" # Изменён внешний порт
    depends_on:
      - mongodb
      - rabbitmq

  # -------------------------------
  # Gateway
  # -------------------------------
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - domain-service
      - redis

  # -------------------------------
  # OpenSearch
  # -------------------------------
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Str0ng@Passw0rd2025
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enforce_hostname_verification=false
    ports:
      - "9200:9200" # API доступ OpenSearch
      - "9700:9600" # Мониторинг OpenSearch
    volumes:
      - ./opensearch/data:/usr/share/opensearch/data
    networks:
      - monitoring

  # -------------------------------
  # Logstash
  # -------------------------------
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    depends_on:
      - opensearch
    ports:
      - "5044:5044" # Filebeat logs
      - "9610:9600" # Мониторинг Logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    networks:
      - monitoring

  # -------------------------------
  # Kibana
  # -------------------------------
  kibana:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: kibana
    depends_on:
      - opensearch
    ports:
      - "5601:5601" # Web-интерфейс Kibana
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'

  # -------------------------------
  # Prometheus
  # -------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Изменён внешний порт
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  # -------------------------------
  # Grafana
  # -------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Web-интерфейс Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge